### ISSUE TITLE
退会APIにストック情報の削除処理を追加する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-backend#109]
# Doneの定義
- 退会時にストックの情報が削除されているいこと

# 補足情報
ストックの同期処理は機能削除したので、カテゴリとストックの中間テーブルを削除する処理を追加する。

**Comment by kobayashi-m42** [comment]
ストーリーポイントは3を想定🐱

**Comment by keitakn** [comment]
@kobayashi-m42 うん！3で問題なさそうだね🐱！
