### ISSUE TITLE
カテゴライズ済みのストックを取得するAPIのソート順を変更する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-backend#143]
# Doneの定義
- ストックのソート順が、idの降順となっていること

# 補足情報
新しくカテゴライズしたストックが一番下に表示されてしまっているので、ソート順を変更し、先頭に表示されるように修正する。

**Comment by keitakn** [comment]
@kobayashi-m42 うん！2でいけそうだね🐱！
