### ISSUE TITLE
テストケースで設定しているURLを.envから取得するように修正する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-backend#145]
# Doneの定義
- 表題の件が対応されていること

# 補足情報
下記のテストケースにおいて、URLが固定 `http://127.0.0.1`になってしまっている。
`tests/Feature/StockIndexTest.php`
`tests/Feature/StockShowCategorizedTest.php`

**Comment by kobayashi-m42** [comment]
ストーリーポイントは1を想定🐱

**Comment by keitakn** [comment]
@kobayashi-m42 うん！1で問題ないと思う🐱！
