### ISSUE TITLE
Fargateで運用するために環境変数を利用してnginxの設定を変更する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-backend#173]
# Doneの定義
nginxの設定が環境変数によって変更可能となっていること

# 補足情報
Fargate を利用する場合、コンテナ間通信の宛先を`localhost`に設定する必要がある。
しかし、`localhost`固定にしてしまうとローカル環境での確認ができないので、環境変数にを利用して`default.conf`を書き換えられるようにする。

**Comment by kobayashi-m42** [comment]
@keitakn 
調査も必要になると思うからストーリーポイントは5を想定！
ちょっと多いかな？🐱

**Comment by keitakn** [comment]
@kobayashi-m42 

>調査も必要になると思うからストーリーポイントは5を想定！
>ちょっと多いかな？🐱

いや、5で問題ないと思う👌動作確認とか含めるとそのくらいのボリュームありそうだし🐱
