### ISSUE TITLE
Migration用のbuildspec.ymlを作成する

### ISSUE THREAD

**Issue by keitakn** [nekochans/qiita-stocker-backend#178]
# Doneの定義
- https://github.com/nekochans/qiita-stocker-terraform/issues/48 で作成するMigration用のBuildプロジェクトに必要な設定ファイルが追加されている事

# 補足情報
下記の2つを完了させる為にもこの対応が必須。

https://github.com/nekochans/qiita-stocker-terraform/issues/48
https://github.com/nekochans/qiita-stocker-docker/issues/5

**Comment by keitakn** [comment]
@kobayashi-m42 ストーリーポイントは2を想定🐱

**Comment by kobayashi-m42** [comment]
@keitakn うん、2でいいと思う！
