### ISSUE TITLE
USE_IN_DOCKERによる条件分岐を削除する

### ISSUE THREAD

**Issue by keitakn** [nekochans/qiita-stocker-backend#188]
# Doneの定義
- USE_IN_DOCKERによるLoggingの条件分岐が削除されている事

# 補足情報
https://github.com/nekochans/qiita-stocker-backend/pull/186 でも触れているが既にDocker運用が前提になっているので `USE_IN_DOCKER` を削除する。

**Comment by keitakn** [comment]
@kobayashi-m42 ストーリーポイントは2を想定しているよ🐱

**Comment by kobayashi-m42** [comment]
@keitakn 2でいいと思う！🐱
