### ISSUE TITLE
Migration実行時にnpm関連のタスクを実行しないようにする

### ISSUE THREAD

**Issue by keitakn** [nekochans/qiita-stocker-backend#190]
# Doneの定義
- `yarn install` と `yarn run createDotenv:${DEPLOY_STAGE}` が実行されないようになっている事

# 補足情報
https://github.com/nekochans/qiita-stocker-terraform/pull/88 でCodeBuildからParameterStoreを参照するようになったのでわざわざ、`.env` ファイルをコンテナ内で作成する必要性がなくなった為。

https://github.com/nekochans/qiita-stocker-terraform/issues/89 でCodeBuildの環境変数からも削除する予定。

**Comment by keitakn** [comment]
@kobayashi-m42 単純な削除だけだから、ストーリーポイントは1を想定しているよ🐱

**Comment by kobayashi-m42** [comment]
@keitakn うん！1で大丈夫だと思う🐱

**Comment by keitakn** [comment]
# めも

https://github.com/nekochans/qiita-stocker-backend/pull/196 で一緒に対応してしまったのでこちらはクローズ
