### ISSUE TITLE
ECRへのプッシュを行う為のCodeBuild設定ファイルを追加

### ISSUE THREAD

**Issue by keitakn** [nekochans/qiita-stocker-backend#195]
# Doneの定義
- https://github.com/nekochans/qiita-stocker-terraform/issues/82 で定義されるCodeBuildプロジェクトの設定ファイルが追加されている事

# 補足情報
https://github.com/nekochans/qiita-stocker-terraform/issues/82 と同時に進める必要がある。

**Comment by keitakn** [comment]
@kobayashi-m42 ストーリーポイントは1を想定しているよ🐱！

（https://github.com/nekochans/qiita-stocker-terraform/issues/82 と同時に検証していけば設定ファイルの設置自体には時間はかからない想定）

**Comment by kobayashi-m42** [comment]
@keitakn うん！1で大丈夫だと思う！🐱
