### ISSUE TITLE
バリデーションのビジネスロジックをドメイン層に移動する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-backend#45]
# Doneの定義
- アプリケーション層に定義されているバリデーションのビジネスロジックがビジネス層に移動されていること

# 補足情報
- 仕様クラス [参考記事](https://qiita.com/ngmy/items/47d4c554582f868510eb)
- ドメイン層の配下にAccountValidatorクラスの作成

**Comment by keitakn** [comment]
@kobayashi-m42 うん！3で問題ないと思う🐱！
