### ISSUE TITLE
RepositoryクラスでModelNotFoundExceptionをThrowするように修正する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-backend#48]
# Doneの定義
- Repositoryクラスで`Exception`がThrowされている箇所が`ModelNotFoundException`がThrowされるように修正されていること

**Comment by kobayashi-m42** [comment]
ストーリーポイントは、2か3を想定🐱

**Comment by keitakn** [comment]
@kobayashi-m42 個人的には、やり方が明確に決まっているなら2、そうでないなら3かな🐱！
