### ISSUE TITLE
退会APIにカテゴリを削除する処理を追加する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-backend#63]
# Doneの定義
- 退会する際に、カテゴリの情報も削除されていること

**Comment by keitakn** [comment]
@kobayashi-m42 正常にDBから消えているかのテストも必要だからそれ考えると3か5かな🐱？

**Comment by kobayashi-m42** [comment]
@keitakn 
[以下の課題をストーリーポイント 5 と定める](https://github.com/nekochans/nekochans/wiki/Reference-story-point#%E4%BB%A5%E4%B8%8B%E3%81%AE%E8%AA%B2%E9%A1%8C%E3%82%92%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AA%E3%83%BC%E3%83%9D%E3%82%A4%E3%83%B3%E3%83%88-5-%E3%81%A8%E5%AE%9A%E3%82%81%E3%82%8B)より少ないと思うから3にするね！
