### ISSUE TITLE
カテゴリ作成APIのバリデーションを作成する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-backend#68]
# Doneの定義
- バリデーションが作成されていること
- バリデーションエラーの場合、エラーレスポンスが返っていること

**Comment by kobayashi-m42** [comment]
ストーリーポイントは2を想定🐱

**Comment by keitakn** [comment]
@kobayashi-m42 うん！2でいけそうだね🐱！
