### ISSUE TITLE
カラムの最大値を変更する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-backend#80]
# Doneの定義
- カラムの最大値を変更し、767bytes以上の文字列が入らないようになっていること

# 補足情報
- Aurora ServerlessがMySQL5.6互換のため、`ユニーク制約を付けたカラムには767bytesまでしか入らない`というエラーが発生
- カラム最大値がその大きさである必要性がないため、カラムの最大値を変更する

[Laravel5.4 + MySQL5.5.9 でusersテーブルのマイグレーション時に Syntax error](https://qiita.com/beer_geek/items/6e4264db142745ea666f)

**Comment by kobayashi-m42** [comment]
ストーリーポイントは2を想定🐱

**Comment by keitakn** [comment]
@kobayashi-m42 うん！2で問題ないと思う🐱！
