### ISSUE TITLE
ユーザ名の同期処理を作成する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-backend#90]
# Doneの定義
- ログイン時にユーザ名が同期されること

# 補足情報
方針としては、ログインAPIにユーザ名の更新処理を追加する。

**Comment by kobayashi-m42** [comment]
ストーリーポイントは、3を想定🐱

**Comment by keitakn** [comment]
@kobayashi-m42 うん！3で行けそうだね🐱！
